version: '3.1'
services:
  db:
    image: mysql:5.7
    volumes:
      - './test/mysql:/var/lib/mysql'
      - './mysql-dump:/docker-entrypoint-initdb.d'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: itimersalesforce
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    ports:
       - 33066:3306
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    ports:
      - '8081:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
  web:
    depends_on:
      - db
    image: itimer-jdk8
    hostname: itimerjkt.com
    volumes:
      - './target/itimer:/opt/tomcat/webapps/'
    ports:
      - '8082:8080'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: itimersalesforce
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
